### ISSUE TITLE
[wsl]paste from system clipboard without mouse(right click)?

### ISSUE THREAD

**Issue by slin004** [tmux-plugins/tmux-yank#100]
Hi, could you share how to paste from system clipboard without mouse?
something like `prefix + P` paste from system clipboard
in back-end, is there a reverse of `clip.exe` ? `$ paste.exe >> foo.txt`

**Comment by docwhat** [comment]
This plugin is just about copying in various ways; not pasting.

Can you not just use <kbd>Ctrl</kbd>+<kbd>v</kbd>?
