### ISSUE TITLE
Timeline for next release?

### ISSUE THREAD

**Issue by axelson** [tmux-plugins/tmux-yank#101]
Would be nice to have a new release that supports Tmux 2.4. It looks like support is already in `master`. Is there anything in particular holding up the next release?

**Comment by docwhat** [comment]
Good point. I’ll release a new version shortly.

**Comment by docwhat** [comment]
Done: [v2.3.0](https://github.com/tmux-plugins/tmux-yank/releases/tag/v2.3.0)
