### ISSUE TITLE
Copying to both clipboards (primary and clipboard)

### ISSUE THREAD

**Issue by lohfu** [tmux-plugins/tmux-yank#105]
I'm trying to get this plugin to copy to both clipboards using xsel.

I tried to the following line to no avail:

```
set -g @override_copy_command 'tee >(xsel) | xsel -b'
```

How should i be doing this?

**Comment by docwhat** [comment]
I'd suggest writing an executable shell script and putting it someplace like `~/bin`.

You can then test it _outside_ of `tmux-yank` to ensure it works.

Your approach (in `bash`) seems reasonable.
