### ISSUE TITLE
Cannot make it work with zsh

### ISSUE THREAD

**Issue by marianopeck** [tmux-plugins/tmux-yank#107]
Hi guys,

I cannot seem to make this plugin work with `zsh`. It did work for me with `bash`. I am under Linux Mint. I am a bit confused about the `bindkey -e`. Where should I add that exactly? I tried in `.zshrc` but that didn't work. 

Thanks

**Comment by docwhat** [comment]
> I cannot seem to make this plugin work with zsh.

I'm sorry to hear that.  If you can explain how it doesn't work, maybe we can help.

> I am a bit confused about the bindkey -e. Where should I add that exactly? I tried in .zshrc but that didn't work.

Putting it in `~/.zshrc` would work.  It may or may not be related to your problem.

Section 4.1.1 of the [ZSH Guide](http://zsh.sourceforge.net/Guide/zshguide04.html) talks about `bindkey -e`:

> You can make `zle` always use either emacs or vi mode by putting either `bindkey -e` or `bindkey -v`
