### ISSUE TITLE
Incompatibility with 2.7 and set-clipboard

### ISSUE THREAD

**Issue by arooni** [tmux-plugins/tmux-yank#108]
I was told not to have set-clipboard on when I raised this issue in 2.7... is this plugin incompatible? 
 
```sh
LilArooni ~: uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.7-rc
screen-256color
```

https://github.com/tmux/tmux/issues/1351

**Comment by docwhat** [comment]
> is this plugin incompatible?

`tmux-yank` is 100% compatible with TMUX 2.7.

You shouldn't have to change `set-clipboard` from the default if your `$TERM` outside of TMUX is set correctly.
