### ISSUE TITLE
Better vim integration?

### ISSUE THREAD

**Issue by JonnyRa** [tmux-plugins/tmux-yank#111]
Hi

I've just been trying to get things setup so I can copy from vim running under tmux to the system clipboard.

Currently I'm in the position where I can copy from vim to the tmux clipboard and if I copy using 'y' I can get from tmux to the system clipboard, however the issue is that vim writing to the tmux clipboard doesn't also write to the system clipboard.

Is this a configuration issue?  

within vim I'm using 

https://github.com/roxma/vim-tmux-clipboard
and 
'tmux-plugins/vim-tmux-focus-events'

and also tmux-yank.

I have the tmux settings set as follows:
set-clipboard external
focus-events on

I'm using gnome-terminal not xterm and would prefer to keep that.

Is this possible?

Cheers

Jonny

**Comment by JonnyRa** [comment]
tmux version is 2.6.  vim version 8.0

**Comment by docwhat** [comment]
This has nothing to do with tmux-yank; so I'm closing this.

<http://vim.wikia.com/wiki/Accessing_the_system_clipboard> may help.

**Comment by JonnyRa** [comment]
I've just swapped from a linux vm on windows I was accessing via putty to properly booting into ubuntu on a new machine.... It looks like the issue is actually with my version of vim for some reason the default one installed on ubuntu comes with `-clipboard`!

I'll try get hold of a better version!

Thanks for your help!  I probably should have checked the simple things earlier

**Comment by JonnyRa** [comment]
You were right about this, nothing to do with tmux and I didn't need any extra plugins to get it to work!  

Thanks :)
