### ISSUE TITLE
tmux-yank does not work at all

### ISSUE THREAD

**Issue by piotrekfus91** [tmux-plugins/tmux-yank#112]
Hi,

I am trying to use tmux-yank, but it doesn't work at all.

Linux Mint 18.3
KDE + Konsole
Tmux v2.7.
Config: https://github.com/piotrekfus91/dotfiles/blob/master/tmux/.tmux.conf

It doesn't work with and without mouse.
Plugin is present in .tmux/plugins, also copying using enter and pasting using ctrl+] works.
Any ideas what can I check?

**Comment by docwhat** [comment]
To install the plugin, you have to do more than check it out in a directory (e.g. `~/.tmux/plugins`).

See the "Manual Installation" instructions: <https://github.com/tmux-plugins/tmux-yank#manual-installation>

**Comment by piotrekfus91** [comment]
Seems like something was messed up with dependencies (xclip/xsel). Now it works correctly. Thanks.
