### ISSUE TITLE
xsel vs xclip

### ISSUE THREAD

**Issue by sam-lunt** [tmux-plugins/tmux-yank#114]
In the requirements section of the README for Linux (see [here](https://github.com/tmux-plugins/tmux-yank/blob/e8a03cf41d5322330f5b65411bb2f48b2e4d1733/README.md#linux)), it says:

> - `xsel` (recommended) or `xclip`

However, it seems that if both `xclip` and `xsel` are available, `xclip` will be used (see [here](https://github.com/tmux-plugins/tmux-yank/blob/e8a03cf41d5322330f5b65411bb2f48b2e4d1733/scripts/helpers.sh#L135)).

I was wondering:

1. Why is xsel recommended? It seems that both `xclip` and `xsel` support the needed functionality.
2. If `xsel` is recommended, shouldn't it be preferred over `xclip` when both are available?

**Comment by docwhat** [comment]
Good point!
