### ISSUE TITLE
How about transferring tmux's clipboard to system clipboard?

### ISSUE THREAD

**Issue by mortang2410** [tmux-plugins/tmux-yank#116]
First off, I love this plugin, as it allows me to use WSL on Windows effectively. 
However, is there a way to transfer the contents of tmux's own clipboard to the system clipboard? Pasting with tmux then yanking with yank-tmux doesn't sound very efficient. Is there a setting or key that I'm unaware of?

**Comment by docwhat** [comment]
That’s really a tmux question. You could try there. 

I think you can use the command line to emit the tmux copy buffer.
