### ISSUE TITLE
Select and Copy from Remote Session

### ISSUE THREAD

**Issue by faxotherapy** [tmux-plugins/tmux-yank#117]
Hi,
thanks a lot for the plug-in. I'd like to select text and copy (transfer) it from a **remote** session to my **local** session. Although the method presented below works successfully for me I'd like to know your opinion on its last two steps; steps 3 and 4.

The first boring steps:

1. Setup network listener on my **local** machine ([MacOS](https://apple.stackexchange.com/questions/257609/how-do-i-copy-to-the-osx-clipboard-from-a-remote-shell-using-iterm2/258168#258168), [Linux](https://hackernoon.com/tmux-in-practice-copy-text-from-remote-session-using-ssh-remote-tunnel-and-systemd-service-dd3c51bca1fa)). I use, for example, port 9999 as listen port.
2. SSH to my **remote** machine with `remoteforward=9997 localhost:9999` set in my SSH *config* file. FYI: if no *config* file, then: `ssh -R 9997:localhost:9999 …@…`

The fun part…

3. I add *tmux-yank* plug-in on both my **local** and **remote** machines.
4. I insert `set -g @override_copy_command 'nc localhost 9997'` in my **remote** *tmux.conf* file and reload.

**Comment by bruno-** [comment]
Hey,

that looks pretty cool. I think the last 2 steps are fine.
Feel free to submit a docs PR and expand on this so others can do similar things. I propose making it a markdown file `docs/copy_from_remote_session.md`

**Comment by NitroCao** [comment]
Hi @faxotherapy , I followed the 4 steps but it still did not work, can you describe the first step more detailedly?

**Comment by faxotherapy** [comment]
Hello, I only have implemented the function on my MacOS platform. I haven't tried under GNU/Linux.

I created a file called _local.pbcopy.9999.plist_ with the [following content](https://apple.stackexchange.com/a/258168):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>local.pbcopy.9999</string>
    <key>Program</key>
    <string>/usr/bin/pbcopy</string>
    <key>StandardOutPath</key>
    <string>/tmp/pb9999.out</string>
    <key>StandardErrorPath</key>
    <string>/tmp/pb9999.err</string>
    <key>Sockets</key>
    <dict>
        <key>Listeners</key>
        <dict>
            <key>SockNodeName</key>
            <string>localhost</string>
            <key>SockServiceName</key>
            <string>9999</string>
        </dict>
    </dict>
    <key>inetdCompatibility</key>
    <dict>
        <key>Wait</key>
        <false/>
    </dict>
</dict>
</plist>
```

Then, I put the file in folder `~/Library/LaunchAgents` so that the listener is enabled every time a user session is started. However, for the current session, I can start it immediately with:
```shell
$ cd ~/Library/LaunchAgents
$ launchctl load local.pbcopy.9999.plist
$ launchctl list | grep 9999
-       0       local.pbcopy.9999
```

`unload` to mute the listening port for the current session.
