### ISSUE TITLE
copy-mode y not working in tmux 3.0

### ISSUE THREAD

**Issue by jayywolff** [tmux-plugins/tmux-yank#132]
After updating tmux to 3.0 nothing happens when you attempt to yank text

System Specs:
Arch Linux
termite 15-1
tmux 3.0
xsel 1.2.0

**Comment by oblitum** [comment]
Same here... Here we go again.

**Comment by eric-pigeon** [comment]
It's a problem with `tmux_is_at_least` in `scripts/helpers.sh` you temporarily change the body to `return 0` until someone works on a PR

**Comment by iovis** [comment]
I think tmux 3.0a resolves the issue, I just tested

**Comment by oblitum** [comment]
Indeed, this is fixed on 3.0a. Arch repos just upgraded.

**Comment by davidpdrsn** [comment]
Any hints on how to install that on Mac?

**Comment by iovis** [comment]
> Any hints on how to install that on Mac?

`brew install tmux` is a quick one
