### ISSUE TITLE
tmux-yank stuck in copy mode

### ISSUE THREAD

**Issue by JadeRing** [tmux-plugins/tmux-yank#135]
everything is normal when i select less than three lines.
but if i selected more than three lines, tmux stuck in copy mode after i press y. (both Ctrl+c and Enter no response)
i have to close the window to exit tmux.

![image](https://user-images.githubusercontent.com/38696086/71677217-3802d500-2dbd-11ea-9841-daabfe412439.png)

**Comment by JadeRing** [comment]
![image](https://user-images.githubusercontent.com/38696086/71677363-9f208980-2dbd-11ea-92bc-0a9bc03444b4.png)

here is my environment, this issue came out after i updated manjaro recently.

**Comment by k1sul1** [comment]
Just noticed the same thing. Thought it was an isolated incident when it happened once but when it happened again I realised it's not. 

I'm also running Manjaro on this particular machine. 

```
❯ tmux -V
tmux 3.0a
```

As a "workaround", I open another terminal and type `tmux attach` into it, and then close the frozen terminal.

**Comment by elijahkim** [comment]
Just got a fresh install of Manjaro and it's crashing for me too. I'm trying to get logs but am unable to get those as well.

**Comment by nicm** [comment]
Are you using Konsole? This is probably https://bugs.kde.org/show_bug.cgi?id=415249.

**Comment by elijahkim** [comment]
yep that seems like it to me. I installed kitty and that freezing stopped

**Comment by k1sul1** [comment]
Time for a rollback. I've tried all of the terminal emulators and konsole is the one for me. Thanks for the tip.

**Comment by k1sul1** [comment]
It was fixed 3 days ago, but it hasn't been updated to arch repos: https://www.archlinux.org/packages/extra/x86_64/konsole/

I guess I'll build it myself.

**Comment by JadeRing** [comment]
@nicm 

> Are you using Konsole? This is probably https://bugs.kde.org/show_bug.cgi?id=415249.

You are right, this issue disappeared when i use terminator. 
Thanks a million !

**Comment by JadeRing** [comment]
> It was fixed 3 days ago, but it hasn't been updated to arch repos: https://www.archlinux.org/packages/extra/x86_64/konsole/
> 
> I guess I'll build it myself.

That will be great. Looking forward to it.
