### ISSUE TITLE
Yank not working for remote server

### ISSUE THREAD

**Issue by paymog** [tmux-plugins/tmux-yank#157]
I use tmux yank on my mac and now I've installed it on a remote server running ubuntu 21. I'm connected to the remote server using mosh (which is supposedly supported by tmux yank). I've verified that tmux-yank is correctly installed as a tmux plugin. I've also installed `xsel` and `xclip`. However, when I try to yank some selection, nothing gets put into the clipboard of my mac.

Anyone know how I can debug this? Are there logs for tmux-yank I can read? Is this a known problem? Do I need any other software on the remote machine or my mac?

**Comment by bruno-** [comment]
> I use tmux yank on my mac and now I've installed it on a remote server running ubuntu 21. I'm connected to the remote server using mosh (which is supposedly supported by tmux yank)

The scenario you're bringing up is NOT supported. This scenario is supported:

- You're running tmux  on a local machine. You have tmux-yank installed.
- You connect to the remote server using mosh.
