### ISSUE TITLE
tmux yank no longer working

### ISSUE THREAD

**Issue by jamesla** [tmux-plugins/tmux-yank#172]
Have recently updated system and everything else clipboard is working fine however the tmux yank is no longer copying.

Not actually even sure how to troubleshoot as it just fails silently and I can't find an error message in logs etc.

What is the best way to troubleshoot tmux yank?

**Comment by anakimluke** [comment]
What OS version are you on? And is tmux-yank updated? (prefix-u to update it if you are using TPM)

**Comment by jamesla** [comment]
I'm on nixos and I'm using the tmux-yank nix package (which follows the manual installation method).

Is there anyway to show what plugins are loaded when done manually?

**Comment by DANic-git** [comment]
The same on me on WSL Ubuntu 22.04
Issue after update to [VScode 1.82.0 ](https://code.visualstudio.com/updates/v1_82)
May related with [Disable bracketed paste mode](https://code.visualstudio.com/updates/v1_82#_disable-bracketed-paste-mode)

**Comment by anakimluke** [comment]
The nix package seems to be either old or misconfigured. I tested on nixos with the packages tmux and tmuxPlugins.yank and couldn't get it to work. Using only the nix package tmux and installing tmux-yank following the manual installation instructions on this repo I get normal behavior. 

@jamesla maybe move this issue to nixpkgs?

@DANic-git are you using nix as well?

**Comment by DANic-git** [comment]
I use VScode integrated terminal with WSL Ubuntu issue related with https://github.com/microsoft/vscode/issues/192518

**Comment by jamesla** [comment]
> The nix package seems to be either old or misconfigured. I tested on nixos with the packages tmux and tmuxPlugins.yank and couldn't get it to work. Using only the nix package tmux and installing tmux-yank following the manual installation instructions on this repo I get normal behavior.
> 
> @jamesla maybe move this issue to nixpkgs?
> 
> @DANic-git are you using nix as well?

I've just overridden that outdated nix package to use the latest version of tmux yank `acfd36e4fcba99f8310a7dfb432111c242fe7392` which is the latest commit on master however still not working.

Is there any way from within tmux to see what version of yank is being installed?

**Comment by anakimluke** [comment]
> Is there any way from within tmux to see what version of yank is being installed?

Hmm I don't think so. Unless using tpm, installing a package simply means running a bash script.

Can you roll back to the last version you had it working? I don't know much about nix so I can't help here.

**Comment by jamesla** [comment]
Unfortunately I can't roll back so only option is to fix this.

are there any debug style commands that I can use to try and provoke the yank plugin into giving me an error message or something?

**Comment by lh0n** [comment]
In my case, yanking stopped working only over an SSH/Mosh session. Locally, it works.

### Remote host

* Both `xsel` and `xclip` installed.
* `~/.tmux.conf` relevant contents

```
set -as terminal-features ',*:clipboard'

[..]

set -g @plugin 'tmux-plugins/tmux-yank'
[..]
```

* Additional Info

```shell
$ tmux -V
tmux 3.3a
```

```shell
$ tmux show -s set-clipboard
set-clipboard external
```

```shell
$ tmux show -s copy-command
copy-command ''
```

```shell
$ tmux info | grep 'Ms:'
 192: Ms: (string) \033]52;%p1%s;%p2%s\a
```

Anything else I could provide to aid in debugging?

**Comment by anakimluke** [comment]
@lh0n It is expected for tmux-yank not to work if used inside an ssh session. By default the remote system doesn't have access to your local system's clipboard. Try starting tmux first, *then* connecting to the ssh session :)

**Comment by lh0n** [comment]
@anakimluke It works just fine! That's what this line is for in the config.

```
set -as terminal-features ',*:clipboard'
```

**Comment by anakimluke** [comment]
@lh0n What I meant is that your problem is different than the one discussed in this issue. You can create a feature request if you want :) Though I think it'd be more productive for you to google ways of sharing the clipboard between the local host and the host connected via ssh. Probably using X forwarding should work for you, if you trust the remote machine(because of the security concerns that X forwarding can bring). There seems to be other alternatives too; here some results from a brief google search: [wincent/clipper](https://github.com/wincent/clipper), [haya14busa/vim-poweryank](https://github.com/haya14busa/vim-poweryank) and [fcpg/vim-osc52](https://github.com/fcpg/vim-osc52). I haven't used those tools so I can't help with the specifics ;)

**Comment by jrusz** [comment]
I've had a similar issue where after updating the system the `tmux-yank` stopped working for me. I finally got so annoyed that I decided to fix it and after some googling and trial and error I managed to fix it by adding these to my `.tmux.conf`
```
set -g set-clipboard on

set -g @override_copy_command 'xclip -i -selection clipboard'

set -g @yank_selection 'clipboard'

set -as terminal-features ',*:clipboard'
```
Not sure if all of them are necessary but I don't want to touch it anymore, it works now. Hope it helps someone.

**Comment by trb143** [comment]
I have been having the same issue with Fedora 39 and Kali both running KDE.
My terminal was konsole and tmux-yank to clipboard did not work.
Moving to KITTY has resolved this with no change to the config.  I have tested under wayland and.

**Comment by T4puSD** [comment]
I am also facing this issue recently in my Arch Linux. I use alacritty as my main terminal. I even tried with kitty as suggested by @trb143 but faced same issue. I was able to fix it temporary by applying fix provided by @jrusz .

**Comment by xxCosta** [comment]
Moving to kitty and using @jrusz settings fixed my issue. Using fedora 40, was using gnome terminal when yank was not working.

**Comment by HarshaGD1997** [comment]
I had similar issue, the solution provided by @jrusz  fixed the issue

**Comment by TheNilesh** [comment]
When I switched from Wayland to X11 on Ubuntu, `tmux-yank` stopped working. However, after switching back to Wayland, it started working again. Does anyone know how to configure `tmux-yank` to automatically use `xclip` or `wl-copy` based on the active windowing system?

**Comment by mplieske** [comment]
On Fedora 41 I had the same issue.

I could manage getting it to work with almost the same settings as @jrusz, thanks 😄

xclip is not preinstalled on fedora workstation 41, so first of all install that:
```
sudo dnf install -y xclip
```

The `@override_copy_command` was not good for me. The clipboard itself is not accessed the way I expacted it in the tmux session somehow. However copying to the primary selection as well as the clipboard enabled me to paste the copied contents inside and outside of tmux.

So the configuration looks like this now:
```
# Enable clipboard
set -g set-clipboard on
set -g @override_copy_command 'xclip -i -sel p -f | xclip -i -sel c'
set -g @yank_selection 'clipboard'
set-option -sa terminal-features ',*:clipboard'
```

Hope it helps

**Comment by harilvfs** [comment]
@mplieske  Thanks, man! This worked for me. I don’t know what happened—it just stopped working, but with this setup:

```sh
# Enable clipboard
set -g set-clipboard on
set -g @override_copy_command 'xclip -i -sel p -f | xclip -i -sel c'
set -g @yank_selection 'clipboard'
set-option -sa terminal-features ',*:clipboard'
```

it's working fine now!
