### ISSUE TITLE
How to yank to buffer & clipboard at the same time?

### ISSUE THREAD

**Issue by rolfschr** [tmux-plugins/tmux-yank#173]
Hi,

is it possible to bind a key to directly both yanking to the clibpoard (using this plugin) and copying to the buffer? I do not want to decide in advance whether I need to press `Enter` or `y` basically.

I'm sorry if this is obvious or already explained somewhere, I haven't found anything here.

Thanks for the work in any case!

**Comment by anakimluke** [comment]
What I do instead is to remap a `<prefix>]` to paste the clipboard instead in place of the current buffer. 

```
bind-key -r ] run "tmux set-buffer \"$(xsel --output --clipboard)\" ; tmux paste-buffer"
bind-key -r C-] run "tmux set-buffer \"$(xsel --output --clipboard)\" ; tmux paste-buffer"
```

I also bind `c-]` so that you don't need to let go of the control key to press ]. kinda useful

**Comment by rolfschr** [comment]
Hi @anakimluke I don't really understand your comment but I realized that `tmux-yank` anyways copies to the clipboard as well as to the tmux buffer by pressing `y`. So with `set -g @copy_mode_yank Enter` I can press `Enter` (more reachable I feel than `y`) and have the selection copied to both clipboard and tmux buffer.
