### ISSUE TITLE
server exited unexpectedly

### ISSUE THREAD

**Issue by faxotherapy** [tmux-plugins/tmux-yank#179]
Using mouse pointer to select an entry in tmux. Suddenly, tmux crashes. I can no longer user my pointer to select anything inside tmux. Every time I try to select a thing, tmux crashes and I have the following message: `server exited unexpectedly`

I have to toggle the mouse off. It used to work, but today, for unknown reasons to me, no longer working. I've had no problem during these past 4 years. Any clue?

Context: macOS Monterey, issue happens with any Terminal app (iTerm, Terminal, etc.)

Logs: (trying to attach logs here, but now working. Where can I upload logs? Thank you)

**Comment by y-a-n-n** [comment]
Was there a solution for this? I am seeing the same issue

**Comment by faxotherapy** [comment]
My _ncurses_ version was too new in my case. I had to upgrade _tmux_ to the very latest version (hence forcing to rework a bit some of the entries in my _tmux_ conf file)
