### ISSUE TITLE
`unbind -T copy-mode-vi MouseDragEnd1Pane` no longer works?

### ISSUE THREAD

**Issue by shinebayar-g** [tmux-plugins/tmux-yank#182]
I had `unbind -T copy-mode-vi MouseDragEnd1Pane` in my tmux config to not jump the cursor to the bottom when I select something.

However, after I install the plugin, the behavior is back. Whenever I select something, cursor immediately jumps to the bottom. How can I disable this?

**Comment by returnDanilo** [comment]
Try setting `set -g @yank_action 'copy-pipe'`. Make sure this line is before the line in the config file where the plugin is sourced.

**Comment by shinebayar-g** [comment]
Yay that worked! Thanks.
