### ISSUE TITLE
Mouse mode support

### ISSUE THREAD

**Issue by duffytilleman** [tmux-plugins/tmux-yank#24]
I'm not sure if this is a missing feature, or just an issue with my setup.  I have tmux-yank working great using the following steps:  enter copy mode, select text, press 'y'.  However, when I select text using the mouse that text makes it into the tmux paste buffer, but not my system clipboard.

I'm on OS X, using iTerm2 and tmux 1.9a.  Possibly relevant section of my .tmux-config:

```
bind-key [ copy-mode
bind-key p paste-buffer
bind-key -t vi-copy '=' rectangle-toggle
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection
set-option -g mouse-select-pane on
set-option -g mouse-select-window on
set-option -g mouse-resize-pane on
set-option -g mouse-resize-pane on
set-option -g mode-mouse on
```

**Comment by bruno-** [comment]
I think we solved this one.

https://github.com/tmux-plugins/tmux-yank#notes
