### ISSUE TITLE
Prefix+y assumes the shell uses Emacs key bindings

### ISSUE THREAD

**Issue by rkennedy** [tmux-plugins/tmux-yank#33]
Consider the case when bash is set to use vi key bindings in *.inputrc* file:

```readline
set editing-mode vi
```

That setting causes this plugin's prefix+y command to fail. Instead of copying the current command line, it writes `^A^E` to the screen, and places the single character `A` on the clipboard.

This is similar, but not identical, to issue #22. That one is caused by assuming certain tmux bindings; this one is from assuming certain shell bindings.

**Comment by bruno-** [comment]
Hi,
yes, emacs key bindings are assumed.
I've just added a note to the readme, hopefully it's clear now.

**Comment by bruno-** [comment]
Hi, we're working on `vi` mode support in #37. This should be merged soon.
