### ISSUE TITLE
new-lines are lost

### ISSUE THREAD

**Issue by gaydenko** [tmux-plugins/tmux-yank#34]
Arch Linux is in use. Pasting copied text into, say, `geany` or `emacs` (with `xclip.el`) results in a single line instead of a text. 
![tmux-yank01](https://cloud.githubusercontent.com/assets/3740016/8132108/05157d70-1128-11e5-9dea-62cd1c6987c0.jpg)

**Comment by bruno-** [comment]
Hi,
which command are you using?

The `prefix + y` (copy text from newline to clipboard) does have newline removal. That way when command is long and text is wrapped, it will not contain newlines because the user never entered them.

I can't reproduce this with copy mode commands (`y` and `Y`).

**Comment by gaydenko** [comment]
Hi,
Screenshots are filled with man fragment, that is copy mode was in use with `y` command.
To be honest, at the moment I have suspended tmux using, so the issue can be safely closed as far as I'm the only affected.
