### ISSUE TITLE
Feature request: tmux-paste

### ISSUE THREAD

**Issue by snowch** [tmux-plugins/tmux-yank#38]
It would be great if this plug could also paste from the system buffer :)

**Comment by bruno-** [comment]
Hmm.. what would be the use case?
Can't you just `ctrl-v` or or mac `cmd-v` and that's it?

**Comment by akheron** [comment]
Some terminals (e.g. Linux urxvt) don't support any form of interaction with the clipboard. Shift+insert and mouse middle button work for pasting from the PRIMARY buffer, though.

**Comment by dcelasun** [comment]
This would be a great addition. Like @akheron said, urxvt's interaction with the outside environment is quite limited, so this would be very useful.

**Comment by arnm** [comment]
+1

**Comment by LukaK** [comment]
+1

**Comment by docwhat** [comment]
I feel like this is outside the scope of `tmux-yank`.

If you want, you can use bind a key to a simple shell script (untested) like:

``` sh
# Save the contents of `pbpaste` (the macOS pastboard) to a buffer called system-clipboard.
tmux set-buffer -b 'system-clipboard' "$(pbpaste)"
# Paste the system-clipboard buffer into the current pane.
tmux paste-buffer -b 'system-clipboard'
```

**Comment by docwhat** [comment]
Closing as "outside the scope of tmux-yank".  You can bind a key in tmux to run whatever your Operating System's "paste" is (see the above comment).

If someone writes up some examples, I'm happy to take it as part of an FAQ for the documentation.

Equally, if someone has a convincing argument I'm happy to reopen this.

**Comment by miki725** [comment]
https://github.com/brennanfee/tmux-paste

this plugin adds requested functionality. posting here for future reference if people come across this issue

**Comment by bruno-** [comment]
Consider adding it to the [plugins list](https://github.com/tmux-plugins/list)
