### ISSUE TITLE
Copying visual selection in Vim without line numbers

### ISSUE THREAD

**Issue by andyatkinson** [tmux-plugins/tmux-yank#39]
Hello. Great plugin, thanks! I'm finding if I enter copy mode (`leader+Esc` for me) first, make a visual selection, then `y` to yank, it saves to the OS X clipboard. The downside is it includes line numbers that were in the visual selection unless I turn them off first.

If I make the visual selection first, which ignores the line numbers, then enter copy mode, press `y`, it doesn't save to the OS X clipboard.

For now I can disable line numbers, enter copy mode, make the visual selection, and yank to the system clipboard. I'd love to be able to cut down those steps. Or maybe I'm doing something wrong. Do you have any suggestions?

Thanks.

`$ VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 20 2014 16:06:46)
MacOS X (unix) version`

`$ tmux -V
tmux 1.9a`

**Comment by netei** [comment]
Are you using tmux-yank to copy text from vim ? Do you know that you could be yanking directly from vim by doing 

 * `Control-v`
 * Select with hjkl
 * `"+y` to yank to the system clipboard

**Comment by andyatkinson** [comment]
@netei Nice! :heart: Somehow I forgot this, despite having [written it in my vim notes](https://github.com/andyatkinson/dotfiles#vim) over a year ago. I guess I thought this didn't work inside tmux, but I confirmed it works the same whether vim is running inside tmux or is not. Thanks!
