### ISSUE TITLE
Stay at copy-mode after yanking

### ISSUE THREAD

**Issue by phphong** [tmux-plugins/tmux-yank#40]
There are times I want to copy text into clipboard, paste somewhere, and then again, in the same position in the history scrollback, copy another text, paste somewhere else, and so on. Is there any option that I can stay at copy mode after yanking text? Otherwise I have to scrollback to the same history position repeatedly.

**Comment by atweiden** [comment]
Seconded, and I was going to open a new issue about this before I saw yours. It's a major annoyance to always lose my position in the scrollback history when yanking text. This plugin is marvelous, but I have to say I really wish this would be fixed.

**Comment by bruno-** [comment]
Hey guys, yea, I want this too.

Unfortunately, I'm not sure if this can be done on the "plugin level". Tmux core just does not expose the functionality that would enable this, I checked with tmux author on irc once.

Specifically, `copy-pipe` command \*always* exits copy mode - that's how tmux works.

Maybe you wanna check or ask for this feature on [https://groups.google.com/forum/#!forum/tmux-users](tmux-users mailing list).

**Comment by bruno-** [comment]
Ups, I messed up the link, here's the correct one for [tmux-users mailing list](https://groups.google.com/forum/#!forum/tmux-users).

**Comment by ntnn** [comment]
That has been implemented with the `-x` flag.
IIRC it has been added about five to six months ago, but I can't remember it being featured in the changelog.

**Comment by atweiden** [comment]
copy-selection? https://github.com/tmux/tmux/issues/129#issuecomment-144793215

**Comment by bruno-** [comment]
Thank you for being proactive about this @atweiden.

So it seems the `-x` flag will be available in tmux 2.1 release. I don't see it in docs for tmux 2.0 (the latest stable version at the moment).

From what I know, we can't use `copy-selection` for yanking to system clipboard, so `-x` flag is of no use for that one. We need the `-x` flag on `copy-pipe` command. `copy-pipe` invokes `pbcopy` or `xclip`.

**Comment by atweiden** [comment]
This feature (and others) may be more easily addressable through [tmux extended with TCL scripting](https://github.com/ershov/tmux/blob/master/README-tmux-scripting.pod).

**Comment by alps2006** [comment]
I modify tmux 2.2 source to resolve the question.
open window-copy.c file.
modify result.

	case MODEKEYCOPY_COPYPIPE:
		if (sess != NULL) {
			window_copy_copy_pipe(wp, sess, NULL, arg);
                       // window_pane_reset_mode(wp);
			window_copy_clear_selection(wp);
			window_copy_redraw_screen(wp);
		}
		break;

**Comment by amerlyq** [comment]
Maybe, instead of fixing `copy-pipe -x` which seems impossible for current tmux keybinding, we could introduce somewhat smaller fix/patch for tmux, to make chain of commands -- like `copy-selection -x` or `start-named-buffer` and then send tmux own/named yank buffer to pipe?

**Comment by docwhat** [comment]
So this should be doable via `tmux` 2.4's new distinction between `copy-pipe` and `copy-pipe-and-cancel`.

Anyone interested doing a PR for it?

**Comment by danielmanesku** [comment]
Are there any updates on this? 
Having this fixed would be very convenient.

**Comment by maximbaz** [comment]
I think PR #104 fixes this issue.

**Comment by docwhat** [comment]
PR #104 is merged please test.

**Comment by docwhat** [comment]
@maximbaz There is still a problem, see @yevhen-m's [comment](/tmux-plugins/tmux-yank/pull/104#issuecomment-374320207):

> I've tried to set
>
> ```sh
> # tmux-yank settings
> set -g @yank_action 'copy-pipe'
> ```
>
> But I still get kicked out from copy mode after I press y or release mouse selection. What am I doing wrong?

**Comment by maximbaz** [comment]
As we figured out in #104, the PR does allow to keep the selection. Now depending on how you configure `@yank_action` you can get different behaviors:

- Copy and scroll down (`copy-pipe-and-cancel`)
- Copy and keep the selection (`copy-pipe`)

Would be cool to know how to combine `copy-pipe` and `clear-selection` so that the selection is cleared, but tmux is not scrolling down, but I don't know the proper syntax.

Regardless, it's not a problem of `tmux-yank` anymore, it's a matter of how to use its available configuration option to achieve your desired behavior.

**Comment by docwhat** [comment]
👍 Closing. :-)

**Comment by offero** [comment]
I also would like to know how to set the command to be copy-pipe followed by clear-selection.

@maximbaz Did you ever figure that out?

**Comment by yevhen-m** [comment]
@offero this works for me:
```
# tmux yank mappings with clear-selection
bind-key -T copy-mode y send-keys -X copy-pipe "reattach-to-user-namespace pbcopy" \; send-keys -X clear-selection
bind-key -T copy-mode Y send-keys -X copy-pipe-and-cancel "tmux paste-buffer"
bind-key -T copy-mode-vi y send-keys -X copy-pipe "reattach-to-user-namespace pbcopy" \; send-keys -X clear-selection
bind-key -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "tmux paste-buffer"
```

**Comment by dylan-chong** [comment]
@yevhen-m Seems to work for me on mac, but can you also make it work for mouse selection?
