### ISSUE TITLE
No newline support

### ISSUE THREAD

**Issue by jessehudl** [tmux-plugins/tmux-yank#42]
tmux-yank doesn't seem to support newlines. For instance, have this output in a tmux session:

```
$ for i in {1..10}; do echo $i; done
1
2
3
4
5
6
7
8
9
10
```

Use tmux copy mode to highlight the all of the lines, then tmux-yank it with `prefix-y`. When you paste it into another program (like a plain text editor), this is what you get:

```
$ for i in {1..10}; do echo $i; done12345678910
```

I had been using this method to get tmux output into the system buffer, which **does** support newlines - https://robots.thoughtbot.com/how-to-copy-and-paste-with-tmux-on-mac-os-x

**Comment by netei** [comment]
Could you try doing  

    tmux save-buffer /tmp/buffer
    cat /tmp/buffer -A

to see if they are really no new lines ?

**Comment by bruno-** [comment]
Hey @jessehudl,
hmm, I just tested that and things worked fine. When pasted to vim, each number was in it's own line.

Can you please paste the output of the following command (please change `vi-copy` to `emacs-copy` if you're using emacs copy mode):

    tmux list-keys -t vi-copy | grep -i 'y copy-pipe'

**Comment by tiensonqin** [comment]
I can confirm this.

**Comment by dshcherb** [comment]
It worked for me once or twice but I mostly get the following result:

This:
0 packages can be updated.
0 updates are security updates.

administrator@ubuntu:~$ 

is stripped of newlines after copying:

0 packages can be updated.0 updates are security updates.administrator@ubuntu:~$

**Comment by dshcherb** [comment]
@jessehudl, by the way 
```
administrator@ubuntu:~$ tmux list-keys -t vi-copy | grep -i 'y copy-pipe'
bind-key -t vi-copy      Y copy-pipe "tmux paste-buffer"
bind-key -t vi-copy      y copy-pipe "xclip -selection clipboard"
bind-key -t vi-copy    M-y copy-pipe "xclip -selection clipboard; tmux paste-buffer"
```

**Comment by dshcherb** [comment]
Tried with xsel instead of xclip as well (I am using byobu with tmux by the way):
```

administrator@ubuntu:~$ tmux list-keys -t vi-copy | grep -i 'y copy-pipe'
bind-key -t vi-copy      Y copy-pipe "tmux paste-buffer"
bind-key -t vi-copy      y copy-pipe "xsel -i --clipboard"
bind-key -t vi-copy    M-y copy-pipe "xsel -i --clipboard; tmux paste-buffer"
```

```
# still on a single line
administrator@ubuntu:~$ cat
bind-key -t vi-copy      Y copy-pipe "tmux paste-buffer"bind-key -t vi-copy      y copy-pipe "xsel -i --clipboard"bind-key -t vi-copy    M-y copy-pipe "xsel -i --clipboard; tmux paste-buffer"administrator@ubuntu:~$
```

**Comment by jessehudl** [comment]
Sorry for the delay in replying.

@dshcherb:
```
$ tmux list-keys -t vi-copy | grep -i 'y copy-pipe'
bind-key -t vi-copy      Y copy-pipe "tmux paste-buffer"
bind-key -t vi-copy      y copy-pipe "reattach-to-user-namespace pbcopy"
bind-key -t vi-copy    M-y copy-pipe "reattach-to-user-namespace pbcopy; tmux paste-buffer"
```

@netei it does seem like the newlines are there:
```
$ tmux save-buffer /tmp/buffer 
$ cat /tmp/buffer
$ for i in {1..10}; do echo $i; done
1
2
3
4
5
6
7
8
9
10
```

But I'm not sure why when I paste them into another application like Sublime (or any other application), they are not pasted with it.

**Comment by dshcherb** [comment]
@jessehudl 
I do have the same result with `tmux save-buffer` - the lines are present in the output.

**Comment by jessehudl** [comment]
@dshcherb are you using the tmux `paste-buffer` command, or the system-wide paste (⌘-v or ctrl-v)?

If I copy with tmux-yank, and open vim, when I paste using `paste-buffer` the newlines are there properly, but when I paste using ⌘-v they are not.

Since tmux-yank is meant to copy to the system keyboard so you can paste into other applications outside of tmux/terminal, it doesn't seem to be working properly. Using the method I pasted earlier with `reattach-to-user-namespace` to `pbcopy` does work properly: https://robots.thoughtbot.com/tmux-copy-paste-on-os-x-a-better-future

**Comment by dshcherb** [comment]
@jessehudl its exactly as you describe it: it works when I paste in vim but it does not (always) work when I paste in an editor (e.g. gedit on Ubuntu).

I have newlines now in the pasted output in gedit though I did not 10 minutes ago. I am going to try to reproduce this behavior.

**Comment by dshcherb** [comment]
@jessehudl here is what I found out:
`<prefix> + ]` followed by `y` in the copy mode works for both vim and a gui editor - the newlines are present.
`<prefix> + ]` followed by `<prefix> + y` strips out the newlines.

I can't believe I was hitting the `ctrl` every time I wanted to do a copy of a selection before pressing `y` - shame on me. I don't have a mac lying around to test though.

**Comment by jessehudl** [comment]
@dshcherb interesting. `<prefix> + ]` followed by `y` does *not* preserve newlines for me on OSX, and `<prefix> + ]` followed by `<prefix> + y` doesn't seem to do anything.

**Comment by amerlyq** [comment]
Some new matter on topic. 
```
tmux -> vim = good (as in almost any TUI/CLI)
tmux -> pidign = bad (as in almost any other GUI)
```
BUT!!! if after copy in tmux I will do seemingly meaningless
```bash
xsel -ob | xsel -ib
```
then pasting in pidgin is good again.
System clipboard buffer is byte-identical before and after.
So, when executing  tmux-yank, clipboard content is specifically *tagged* by system.
And that *tag* is read by GUI apps when pasting (whatever that *tag* may mean, I don't know).

We need to go deeper. Under ArchLinux I use only `xsel`, but there is long forgotten `xclip` on my system.
```tmux
set -g @custom_copy_command "xclip -selection clipboard"
set -g @custom_copy_command "xsel -ib"
```
P.S. By the way, `custom_copy_command` must be the first one in fallback order to be able to override your defaults chain by user's wrapper over xsel. Please, smallfix it.

Results: `xsel` good!, `xclip` bad! (no idea why, don't want to submit issue there, I don't use it anyways).

Culprit: `xclip`. So, @bruno-, please, fix this:
* reorder fallback in such a way, that xsel was choosen before xclip for any other oblivious users (xsel is preffered app in linux nowadays).
* fix fallback for `custom_copy_command`, making it first one to always prefer user defaults, instead of only if not found -- generally it's more robust solution.

For all others, until issue is fixed, you have only two choices:
* fix xclip
* don't install xclip -- and fallback will skip it, selecting `xsel`

**Comment by docwhat** [comment]
A PR would be welcome.  The lines in question are https://github.com/tmux-plugins/tmux-yank/blob/master/scripts/helpers.sh#L105-L124
