### ISSUE TITLE
Custom copy command

### ISSUE THREAD

**Issue by netei** [tmux-plugins/tmux-yank#43]
I see in https://github.com/tmux-plugins/tmux-yank/blob/master/yank.tmux#L12

that tmux-yank automatically checks for existing method to access the global clipboard.

```bash
clipboard_copy_command() {
	# installing reattach-to-user-namespace is recommended on OS X
	if command_exists "pbcopy"; then
		if command_exists "reattach-to-user-namespace"; then
			echo "reattach-to-user-namespace pbcopy"
		else
			echo "pbcopy"
		fi
	elif command_exists "xclip"; then
		local xclip_selection="$(yank_selection)"
		echo "xclip -selection $xclip_selection"
	elif command_exists "xsel"; then
		local xsel_selection="$(yank_selection)"
		echo "xsel -i --$xsel_selection"
	fi
}
```

I would like to use another custom command instead (because I'm not allowed to install an xserver on a remote server.

Would you accept a MR that adds a customization possibility to set yourself the command to copy to the system clipboard.

Of course, this configuration would be optional, and if not present, would keep the current behaviour of tmux-yank.

**Comment by bruno-** [comment]
Hi,
thanks for getting involved. Yes, that sounds like a nice feature! Please open a PR.
