### ISSUE TITLE
Enters copy mode after yanking.

### ISSUE THREAD

**Issue by svbatalov** [tmux-plugins/tmux-yank#46]
Hi.
When I press `y` tmux leaves copy mode as expected, but when I release left mouse button after that, tmux enters copy mode **again** displaying `[0/4843]` at top right corner and I have to press escape or `q` to enter normal mode. How to prevent re-entering copy mode?

My setup:
```
$ tmux -V
tmux 2.0
$ cat ~/.tmux.conf
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'

# options
set -g @shell_mode 'vi'
set -g mode-mouse on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by bruno-** [comment]
All looks good with your setup.
Unfortunately I don't know the answer to your question. I find tmux's mouse behavior weird (in particular when mouse button is released).

Tmux 2.1 provides more mouse control and enables custom mouse key bindings.. If you're really into mouse workflow, maybe check that?

**Comment by svbatalov** [comment]
Hi!
I just tried tmux 2.2 (built from master) and it seems to work well so far. Thanks for the suggestion!
