### ISSUE TITLE
xclip seems to hang tmux under Linux

### ISSUE THREAD

**Issue by leoalekseyev** [tmux-plugins/tmux-yank#49]
With tmux 2.1 under Linux I needed to add -b flags to run-shell commands, otherwise tmux clients became unresponsive until the xclip process was killed.  Some background on why this might be happening: http://unix.stackexchange.com/questions/77355/tmux-xclip-copy-no-longer-working

**Comment by bruno-** [comment]
Wanna open a PR?

**Comment by leoalekseyev** [comment]
Opened

**Comment by bruno-** [comment]
PR merged, closing.
