### ISSUE TITLE
Copy current command line is not working

### ISSUE THREAD

**Issue by douglascorrea** [tmux-plugins/tmux-yank#50]
In the screencast video you presented prefix + Y as copying the current command line, but it is now to copy pwd.

If I try simple prefix-y with the current command line, it is not copying it (and it is also puting ^E^A at the end of line).

Is there a way to simple copy the current command line?

**Comment by bruno-** [comment]
It seems readline is not enabled (or not working) for your setup. `readline` is so ubiquitous it's not even mentioned.

The `^E` and `^A` characters are `ctrl-e` and `ctrl-a`. When pressed in the shell (or many other `repl`s) `ctrl-e` moves the cursor to the end of the line and `ctrl-a` moves the cursor to the beginning of the line.
These readline features are used by `tmux-yank` line copy.

The likely solution is to enable readline for your environment (there should be plenty of google support for this). To make sure readline works, try playing with `ctrl-a` and `ctrl-e` and verify those work correctly. After that `tmux-yank` should just work.

I'm doing some issues cleanup. I think the above should work so I'm going to close this issue. Please reopen if you have additional questions or something is still not working.

**Comment by n0nick** [comment]
@bruno- I do have Readline enabled in my terminal, but am using Zsh's Vi bindings [1], so `ctrl-a` and `ctrl-e` do not work and I'm getting the original issue described by @douglascorrea (indeed going back to Emacs binding by `bindkey -e` solves the issue).

Do you think it would be possible to fix the line yank behavior for such bindings? It seems pretty useful :)

[1] http://dougblack.io/words/zsh-vi-mode.html

**Comment by laur89** [comment]
Same here as for @n0nick, but with bash - if vi bindings are enabled (`set -o vi`), then the feature breaks.
