### ISSUE TITLE
release on mouse works on OSX in iterm2 3.x beta

### ISSUE THREAD

**Issue by joemiller** [tmux-plugins/tmux-yank#51]
It appears that it may no longer be necessary to press `y` button to copy into the OSX system clipboard anymore, assuming iterm2 3.x beta and the `'Applications in terminal may access clipboard'` option is enabled in settings.

"works for me". If anyone can confirm, it would be awesome to document and update the README. https://github.com/tmux-plugins/tmux-yank#notes

**Comment by bruno-** [comment]
Oh, I see.. so if I understand it right `iterm` will do the copying from tmux to OSX clipboard?

**Comment by docwhat** [comment]
@joemiller Would you be willing to look at the updated README to see if explains this well enough?

**Comment by joemiller** [comment]
@docwhat 👍
