### ISSUE TITLE
How to make it work over mosh

### ISSUE THREAD

**Issue by tnguyen14** [tmux-plugins/tmux-yank#53]
I am using tmux inside a mosh session to a remote server. I can't seem to be able to copy text by highlighting and press `y` like I would locally. Is there a way to make this work? I am on iTerm2.

**Comment by bruno-** [comment]
Hi,
unfortunately I think this can't be done. The reason is: when you yank text with `y` on the remote server, text is copied to clipboard on the remote server. Your local machine's clipboard is unchanged.

**Comment by tnguyen14** [comment]
I see. I thought the README mentioned that it's tested with mosh?

Also, if I can't automatically put it in the clipboard, is there a way I
can keep the text selection and use a native copy function to read it off
the terminal screen instead?
