### ISSUE TITLE
returned 1 after "run-shell".-

### ISSUE THREAD

**Issue by jimsrc** [tmux-plugins/tmux-yank#54]
Hello!,

After I git clone this repo, I do the:
:run-shell ..../yank.tmux

and I get:
'/home/jim/.tmux/plugins/tmux-yank/yank.tmux' returned 1
Why could this be?

PS: my tmux is installed in userspace. That is, my exe is $HOME/local/bin/tmux_2.1
Thanks in advance!,
Jimmy.

**Comment by docwhat** [comment]
@jimsrc 

Sorry for the long wait for a reply.  Is this still an issue?  You should be able to run `yank.tmux` from a shell (from within `tmux` of course).  Does that show the error?jk
