### ISSUE TITLE
Fedora24: "tmux-yank dependencies not installed!"

### ISSUE THREAD

**Issue by bhilburn** [tmux-plugins/tmux-yank#60]
I've been using `tmux-yank` without issue on Fedora22 for ages. I just upgraded to F24, and unfortunately things aren't working anymore.

I was using `xsel` on F22, but when that didn't seem to work, I tried `xclip`, as well. To be clear, the issue isn't that it invokes the command and the yank / clipboard doesn't work, it's that anytime I try to yank I see the `Error! tmux-yank dependencies not installed!` message.

xsel: `xsel version 1.2.0`
xclip: xclip-0.12-11

Any ideas?

**Comment by dennistang** [comment]
Having the same issue on F24 as well, xsel `1.2.0` and xclip `0.12`.

**Comment by dennistang** [comment]
Would ultimate like to keep using tmux-yank, but as a workaround:
`bind -t vi-copy y copy-pipe 'xclip -in -selection clipboard'`
in the .tmux.conf will do the trick for the time being.

**Comment by bhilburn** [comment]
So a bunch of packages got updated, and suddenly everything works fine for me, now. I'm not really sure what changed? I would close this bug, but will leave it open since it looks like @dennistang might be having issues.

**Comment by docwhat** [comment]
Closing as nobody seems to be having issues anymore.

**Comment by lsc1234582** [comment]
I had the same issue. Make sure you've installed xclip.
