### ISSUE TITLE
Can I copy to clipboard with the mouse ?

### ISSUE THREAD

**Issue by statquant** [tmux-plugins/tmux-yank#65]
I do not know if things are doing what they are supposed to.
Using your addin I can:
1. do Ctrl-A + y and copy in the clipboard what is in the command line
   example>>  statquant $ this is a test // then Ctrl-A + y // then I can paste in another app with Ctrl-V (not middle click)
2. Enter in copy mode and press y to get in the clipboard what highlighted
   example>> Ctrl-A + esc // now hightlight with Ctrl-V // now press y // then I can paste in another app with Ctrl-V (not middle click)

What I'd like would be to highlight with the mouse some text on the window and that this would be copied in the clipboard.
I can do exactly this... but it goes to the tmux clipboard

Can I do that with your plugin ?

**Comment by docwhat** [comment]
This works already; see [mouse support](https://github.com/tmux-plugins/tmux-yank#mouse-support) in the `README`.

In addition, if you use Linux with `xterm` or macOS with `iTerm2` _and_ `tmux` 2.4+ then you can do this natively in `tmux`.  See the `README`.
