### ISSUE TITLE
Copying directory works, but copying selection does not

### ISSUE THREAD

**Issue by felippenardi** [tmux-plugins/tmux-yank#66]
I'm on a El Capitan 10.11.3. The `cmd+Y` works fine and it does copy the text to my clipboard. But selecting something on tmux and then pressing `y` does nothing.

**Comment by Fenkiou** [comment]
I thought I had the same problem with 10.12 but I had to `brew install reattach-to-user-namespace`  as said in the doc THEN restart my terminal application.

And it works.

**Comment by prometheansacrifice** [comment]
I experience the same as @felippenardi I have `reattach-to-user-namespace` installed already. 

Running
tmux 2.3
MacOS Sierra

**Comment by maxcnunes** [comment]
I had to include this `set -g default-command 'reattach-to-user-namespace $SHELL --login'` on [my **.tmux.conf**](https://github.com/maxcnunes/dotfiles/blob/master/tmux/tmux.conf.symlink#L3) to make the yank work properly on Sierra.

**Comment by prometheansacrifice** [comment]
@maxcnunes Same as `set-option -g default-command "reattach-to-user-namespace -l bash"`?

**Comment by maxcnunes** [comment]
What do you mean by same?

**Comment by prometheansacrifice** [comment]
@maxcnunes I already have it in my `.tmux.conf` as directed over [here](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard)

**Comment by maxcnunes** [comment]
Yeah. Looks like the same command. But if I remember well I had tried this command below without success:

```
set-option -g default-command "reattach-to-user-namespace -l zsh"
``` 

Only when I tried  this other one I got it working properly:

```
set -g default-command 'reattach-to-user-namespace $SHELL --login'
``` 

I have not tried on bash though. Only zsh.

**Comment by lfv89** [comment]
I just upgraded my MacOS to Sierra (10.120 and started to have the exactly same problem, even after installing `reattach-to-use-namespace`.

@maxcnunes solution worked perfectly for me though.

**Comment by docwhat** [comment]
It seems like the need for `reattach-to-use-namespace` is needed again in the latest version of macOS?

See <http://stackoverflow.com/questions/39645253/clipboard-failure-in-tmux-vim-after-upgrading-to-macos-sierra/39741226#39741226>

**Comment by docwhat** [comment]
I updated the docs in 15b998050b49484c6994de28743643f790b0fc4a
