### ISSUE TITLE
Yanking command line fails (and appends ^A^E to the line)

### ISSUE THREAD

**Issue by jsalvatier** [tmux-plugins/tmux-yank#68]
When I'm on the command line with

```
$ my command
```

And I press `prefix + y`. I get

```
$ my command^A^E
```

"^A^E" is highlighted and at the bottom of the screen it says "Line copied to clipboard!". The system clipboard doesn't contain "my command" but instead contains "A". 

Any idea what might be going wrong?

I'm on OS X and iTerm2. I've mucked a bit with my iTerm2 `meta` key settings, in case that's relevant.

**Comment by viditochani** [comment]
Are you using bash VI mode? The plugin only seems to be working in normal mode. #48

**Comment by viditochani** [comment]
Are you using VI mode in bash/zsh? The plugin only seems to be working in normal mode.

Refer this issue... #48

**Comment by docwhat** [comment]
If you have `tmux` 2.4+ this works better now.  No more having to set `shell_mode`. 

With `tmux` < 2.4 it is always going to be a bit iffy and annoying.  Sorry.

Fixed by e01284962106089d39cbbff116a11dbfae19713f
