### ISSUE TITLE
Is it possible to make "y" command the same as "Enter" key?

### ISSUE THREAD

**Issue by lccro** [tmux-plugins/tmux-yank#69]
AKA: default copy behavior to copy to clipboard

**Comment by docwhat** [comment]
- <kbd>y</kbd> will copy to the `tmux` copy-and-paste buffer _and_ to the system's clipboard (e.g. `pbcopy` on macOS).
- <kbd>ENTER</kbd> doesn't copy to the system's clipboard.

Are you wanting <kbd>ENTER</kbd> to be the same as <kbd>y</kbd>?

If so, you can change the yank key to `Enter`.  I think like so:

```
# In your ~/.tmux.conf
set -g @copy_mode_yank 'Enter'
```

**Comment by lccro** [comment]
worked like a charm, thanks a ton!
