### ISSUE TITLE
Prefix + y will copy text in the middle all the way down

### ISSUE THREAD

**Issue by rakanalh** [tmux-plugins/tmux-yank#71]
When i am at a second line from a X lines text in tmux copy-mode:

```
Test line 1
Test line 2
Test line 3
```
I enter copy-mode, Prefix-space (emacs) to select test line 2, pressing prefix + y will copy line 2 + line 3 into the clipboard. 
Is that an intended behaviour? otherwise, could you kindly provide some assistance to this issue?

**Comment by rakanalh** [comment]
I believe i was using Prefix-y when i was only supposed to press `y` to copy selected text. But there is a confusion, According to the read me, if i press Prefix-y, it will copy selected text into the clipboard, and in copy-mode, i only need to press `y`. Which brings the question, when is Prefix-y useful if not in copy-mode?

**Comment by rakanalh** [comment]
I believe i was using Prefix-y when i was only supposed to press y to copy selected text.

**Comment by jtmarmon** [comment]
I have the same problem, but when I just press y, it's not copied to my system clipboard, just my tmux one. Anyone have a hunch how to fix this?
