### ISSUE TITLE
"tmux-yank dependencies not installed!" (Ubuntu bash for windows)

### ISSUE THREAD

**Issue by whitecolor** [tmux-plugins/tmux-yank#74]
Ubuntu bash for windows.
tmux 2.0

- Added `set -g @plugin 'tmux-plugins/tmux-yank'` into .tmux.conf
- Press Ctrl+B+I and plugin is installed.
- Enter copy mode `Ctlr+B+[`, select text, and press `Shift+y` and got the error in status bar `Error: tmux-yank dependencies not installed!`

Nothing in system clipboard.

What I'm doing wrong?

**Comment by whitecolor** [comment]
The solution:

- install `tmux-yank` plugin
- install xcopy until: `apt-get install xcopy` 
- add `export DISPLAY=:0` to `~/.bashrc`
- install [Xming X Server for Windows](https://sourceforge.net/projects/xming/)

After this copying using `y` key in `copy` mode of `tmux` should work.

**Comment by mark2185** [comment]
Hello, stumbled upon the same error, but on `centos`?

**Comment by Suraez** [comment]
Or you can install xsel: `sudo apt install xsel`
