### ISSUE TITLE
Add support for WSL using clip.exe

### ISSUE THREAD

**Issue by fpqc** [tmux-plugins/tmux-yank#75]
In Windows subsystem for Linux, you can access native Win32 applications.  In particular, a nice one is clip.exe.  However, unlike xclip and xsel, it only accepts input from stdin, so the syntax is 
`echo "$yank_text" | clip.exe`.  I tried editing the script and couldn't figure out how to get it to work when the piping is like this, so I can't just submit a PR.

**Comment by whitecolor** [comment]
btw I tried to add custom copy command to .tmux.conf: `set -g @custom_copy_command '/mnt/c/Windows/System32/clip.exe'` it doesn't appear in widows clipboard.

**Comment by lukewang1024** [comment]
@fpqc PR #79 has been created for this but it seems like this repo is not actively maintained.

**Comment by docwhat** [comment]
PR #79  is merged.  Closing.

And it is actively maintained again. :smiley:

**Comment by BetterLuke** [comment]
ll

**Comment by BetterLuke** [comment]
I have a method to solve it:   using C-z to make the pane to whole screen. Next , press 'Shift' button and using mouse copy which u want to copy. 😄

**Comment by docwhat** [comment]
@BetterLuke: So was #79 not needed?

**Comment by lukewang1024** [comment]
@BetterLuke what terminal emulator do you use? Is it the native conhost bundled with Windows or Mintty based terminals (like wsltty / wsl-terminal)?

**Comment by fpqc** [comment]
what? this was good. dont listen to betterluke he's just wrong.

He doesn't understand the point of this script at all.

**Comment by BetterLuke** [comment]
@lukewang1024 I'm using he native conhost bundled with Windows.

**Comment by lukewang1024** [comment]
Right. I have also tested it in Mintty-based terminals and it works too. Basically holding SHIFT will trigger the terminal level text select / copy instead. Nice trick but it has nothing to do with what this issue does.

**Comment by francjpd** [comment]
@BetterLuke  Thank you :) you made my night. Been looking for some workaround until this is fixed..
