### ISSUE TITLE
Changes to tmux break copying

### ISSUE THREAD

**Issue by jtbraun** [tmux-plugins/tmux-yank#76]
This commit https://github.com/tmux/tmux/commit/76d6d3641f271be1756e41494960d96714e7ee58 reworks how copy-mode key tables works.  `-t emacs-copy` and `-t vi-copy` are gone, and are roughly replaced with `-Tcopy-mode` and `-Tcopy-mode-vi`.  There are other required changes in how these key bindings work (also summarized in the commit above), requiring the use of `send-keys`.

**Comment by jtbraun** [comment]
It looks like changing most of the commands in yank.tmux from/to below works, using `copy-mode-vi` instead of `vi-copy`.

You probably also want to use the new `copy-pipe-and-cancel` instead of `copy-pipe`.
```bash
tmux bind-key -t emacs-copy KEY COMMAND```
 to
```bash
tmux bind-key -T copy-mode KEY send-keys -X COMMAND
```

**Comment by jtbraun** [comment]
Here's an example set of changes that seem to work.  The final solution should probably detect the tmux version and choose one set of binding commands over another.
https://github.com/jtbraun/tmux-yank/commit/8bd8bb693036c9cfab0395e3b23d95563063dee7

Note that this commit also reflects changes I made to support copy-from-mouse-selection:
https://github.com/jtbraun/tmux-yank/commit/167a85d81b5246dba339759ec418f51f1f4e6f3e

**Comment by yevhen-m** [comment]
Have the same issue, `y` doesn't copy anymore.

**Comment by rcoedo** [comment]
I'm having this issue too.

**Comment by rcoedo** [comment]
If it helps, you can workaround this problem by installing the homebrew package "reattach-to-user-namespace" and adding this two lines to your `tmux.conf`

```
set -g default-shell $SHELL 
set -g default-command "reattach-to-user-namespace -l ${SHELL}"
```

not ideal but it seems to work!

**Comment by directorscut82** [comment]
currently only this works @ubuntu15.10|tmux2.3|fish:
bind-key -T copy-mode-vi y send -X copy-pipe "xclip -sel clip -i"

[TMUX 2.3 copy to clipboard](http://unix.stackexchange.com/questions/317332/tmux-2-3-copy-to-clipboard)

**Comment by oblitum** [comment]
Got here from https://github.com/tmux/tmux/issues/754. ArchLinux has just updated official repositories, triggering this issue.
