### ISSUE TITLE
Doesn't seem to work on Mac OS X 10.12.3 | tmux 2.3 | fish shell 2.4.0

### ISSUE THREAD

**Issue by arooni** [tmux-plugins/tmux-yank#77]
Love using this; have the copycat tmux plugin installed... I can use the copycat version to search and find previous/next selection (very useful)!  But when I try the bindings listed I cannot get my clipboard to change.  I already have reattach-to-namespace and pbcopy pbpaste installed.

What should I do?  I want to take my TMUX POWER TO THE NEXT LEVEL!!! :)

**Comment by directorscut82** [comment]
also not working on ubuntu 15.10 | tmux  2.3 | fish 2.2

**Comment by averrin** [comment]
Dont work on tmux >= 2.2

**Comment by RatanRSur** [comment]
Yeah, I have tmux 2.3 on Arch Linux, also not working

**Comment by docwhat** [comment]
Are you using tmux 2.3 released? Or a nightly build of some kind?

Because tmux 2.4 had a breaking change in its way of assigning keys.  It should be fixed in the `master` branch.

**Comment by Ludachrispeed** [comment]
Also not working for me with tmux 2.4 and fish 2.5.0.

I have been using tmux-yank with fish for a long time on MacOS without problems, but it recently stopped working, probably due to an update of something or other. Still trying to figure out what.

**Comment by docwhat** [comment]
@Ludachrispeed — Glad to see its fixed!

Everyone else:

The current version of tmux-yank is broken with tmux less than 2.4 (my fault, PR #86 will fix it); so this is hard to troubleshoot at the moment.

**Comment by docwhat** [comment]
The current version should be working again.  Please update your plugins and try again.

**Comment by docwhat** [comment]
Works for me with:

- macOS 10.12
- tmux 2.4
- fish 2.5.0

**Comment by arooni** [comment]
Hey docwhat thanks for the update.  

I wanted to update you.  Now I have Fish 2.5.0 ; tmux 2.5 and OS X 10.12.5

In order to get yanking working elsewhere, I have the following config settings for mac os x;
https://gist.github.com/arooni/bdb4e42b02095cd428e0588c9b663635

I can get PREFIX + Y (for cwd) working fine.

but when I do PREFIX + y

It only seems to work if i'm at the beginning of my command line.  If my cursor is at the end of the line then I only seem to get the last character in the line.

**Comment by docwhat** [comment]
@arooni: I opened issue #93 for the prefix-y issue.  Please subscribe to that issue and we'll see what we can do to help you out. 😉

**Comment by arooni** [comment]
Thanks @docwhat  in that case; I'll go ahead and close this issue since we tmux-yank is indeed working now (just not all parts of it :P)
