### ISSUE TITLE
copying text changes large blocks of text with garbage

### ISSUE THREAD

**Issue by RatanRSur** [tmux-plugins/tmux-yank#78]
This only happens when the copied text is at the edge of a pane, causing the garbage text to be drawn over the tmux pane separators and the contents of the other pane.

Some info:
``` 
~ » echo $TERM
tmux-256color
```

**Comment by docwhat** [comment]
- What OS is this?
- What version of TMUX?

I cannot reproduce with macOS and tmux 2.4.

**Comment by CeleritasCelery** [comment]
`set-option -s set-clipboard off`
