### ISSUE TITLE
TMUX-Yank support in Windows Subsystem for LINUIX (WSL / Windows 10)

### ISSUE THREAD

**Issue by itadder** [tmux-plugins/tmux-yank#80]
I would like to know if it would be possible in the new Windows 10 Console and Windows subsystem for Linux if TMUX-Yank support will be available.
TMUX 1.8 is currently running and working. 
Tmux runs on both the Default Console from Microsoft in Windows 10 and using open source console emulator CONEMU.
I have yet to figure out how to get TMUX-Yank to work in Windows Subsystem for Linux.
Which is basically ubuntu Description:    Ubuntu 14.04.5 LTS.

I don't see the requirement needed for WSL or Conemu if there any like on Linux and mac?
Thanks,

**Comment by lukewang1024** [comment]
PR #79 has been created for this purpose. You can do the following till the maintainer merges it:
- Replace `set -g @plugin 'tmux-plugins/tmux-yank'` by `set -g @plugin 'lukewang1024/tmux-yank'` in `.tmux.conf`.
- Remove the currently installed `tmux-yank` manually by `rm -r ~/.tmux/plugins/tmux-yank`.
- Launch tmux and trigger plugin installation.

**Comment by docwhat** [comment]
#79 is merged.  Closing.
