### ISSUE TITLE
copying in copy-mode not working

### ISSUE THREAD

**Issue by pmk1c** [tmux-plugins/tmux-yank#83]
After installing this plugin copying the current working dir will work, pasting will work, but copying in copy mode won't.

I'm on Fedora 25 with tmux 2.3 (also tried 2.2 which is default on F25). I tried with all shells and different terminal emulators. It's always the same. I even tried it in X11 mode (since F25 uses Wayland by default).

I don't get an error. But tmux just won't copy anything into the X buffer.

It seems as if the plugin doesn't even get loaded in copy mode. Since hitting `y` will end the copy mode, but hitting `Y` won't do anything and if I understand correctly this should copy, end copy mode and paste. So even if copying wouldn't work, it should end the copy mode and paste the buffer (since this is working).

**Comment by pmk1c** [comment]
I cleaned up my `.tmux.conf` a bit. Since I had some interferences with old settings. Now it looks like this:

```
# Set C-a as prefix
set -g prefix C-a
bind C-a send-prefix
unbind C-b

# Act like Vim
set-window-option -g mode-keys vi

# Start tab numbering at 1
set -g base-index 1

# Enable mouse
set-option -g mouse on

# Theme
set -g status-bg black
set -g status-fg white
set -g window-status-current-bg green
set -g window-status-current-fg black
set -g status-interval 60
set -g status-left-length 30
set -g status-left '#[fg=green](#S) '
set -g status-right '#{prefix_highlight}#[fg=white]%H:%M#[default]'

# Plugins
set -g @shell_mode 'vi'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
run '~/.tmux/plugins/tpm/tpm
```

But yanking still won't work in copy mode. But now nothing happens when hitting `y` or `Y`

**Comment by mjwhitta** [comment]
Same issue. In case it helps, it looks to be changes in #82 changing to use `send-keys` instead of `copy-pipe` even when older than version 2.4.

**Comment by docwhat** [comment]
@mjwhitta You are correct; I messed up.  Let me fix that...

**Comment by docwhat** [comment]
It should be fixed now.  Update your copy of tmux-yank (e.g. in tmux <kbd>prefix</kbd>–<kbd>U</kbd>)
