### ISSUE TITLE
Mouse mode. Copy to clipboard.

### ISSUE THREAD

**Issue by ltWolfik** [tmux-plugins/tmux-yank#84]
For mouse support It's mentioned: 'press y before releasing mouse.'. It works - and a can type **prefix+]** to paste earlier selected text. Are there something like this for copy to clipboard?

p.s.
'prefix + y - copies text from the command line to clipboard.' - Does not work (I thought prefix: C-a - is the reason, but with another prefix is doesn't work too). After hotkey - tmux appears in copy-mode, and command line filled.

tmux 2.2
OpenSuse Leap 42.2

**Comment by docwhat** [comment]
This may have been due to a bug I put in.

Can you get the latest copy and try again? The _press y before releasing the mouse_ should copy to the clipboard as well, now.

**Comment by ltWolfik** [comment]
So, i've reinstalled tmux-yank by Tmux Plugin Manager. The error remains.

**Comment by docwhat** [comment]
Do you have `xclip` or `xsel` installed?

If you use `xsel`, test this command to see if it pastes "FOOBAR" correctly:

``` sh
$ echo FOOBAR | xsel -i --clipboard
```

If you use `xclip`, test this command to see if it pastes "FOOBAR" correctly:

``` sh
$ echo FOOBAR | xclip -selection clipboard
```

If those don't work, then that is the source of your problem.

If they work with the wrong clipboard (there are several in X-Windows) then you can change it by setting (as per the README):

> ### Linux Clipboards
>
> Linux has several cut-and-paste clipboards: `primary`, `secondary`, and `clipboard`.
>
> You can change this by setting `@yank_selection`:
> 
> ``` tmux
> # ~/.tmux.conf
> 
> set -g @yank_selection 'primary' # or 'secondary' or 'clipboard'
> ```

**Comment by ltWolfik** [comment]
`$ echo FOOBAR | xclip -selection clipboard` - works correctly, but the problem remains.

**Comment by docwhat** [comment]
@ltWolfik I created issue #93 for the prefix-y problem, since it is (most likely) separate.

What terminal emulator are you using? Is it possible that the `y` isn't being sent while using the mouse to select?

**Comment by ltWolfik** [comment]
@docwhat I tested again right now, and now it works correctly with clipboard too! I really don't know why (maybe the problem got solved after some update).
Thanks!

p.s. I use Konsole by KDE

**Comment by docwhat** [comment]
Huh.  Weird. _sigh_
