### ISSUE TITLE
Not working with tmux-2.4 or higher.

### ISSUE THREAD

**Issue by boweevil** [tmux-plugins/tmux-yank#91]
I've compiled tmux 2.2, 2.3, 2.4, & 2.5rc and tested tmux-yank.  Yanking ('y') from copy mode doesn't work in tmux versions 2.4 or higher.  I've only tested this on Arch Linux.

**Comment by boweevil** [comment]
I've now also tested tmux 2.2, 2.3, & 2.4 on Fedora 25.  I get the same results.

**Comment by matt1003** [comment]
I can confirm that tmux-yank does not appear to be working with tmux-next master. I am running on Ubuntu 16.04 LTS and have both xclip and xsel installed. The only functionality that appears to be working is the copy pwd. I have tried using the latest version of tmux-yank (68c5c7ca6f), and it is still not working; however it does work fine with tmux-2.1.

**Comment by rjmccabe3701** [comment]
Just updated to tmux 2.4 in cygwin (from 2.3) -- copy/paste stopped working for me as well.

**Comment by rjmccabe3701** [comment]
Backing of this [change ](https://github.com/tmux-plugins/tmux-yank/commit/fe10415ba090215feba26ea3ae274e93685de0d5 )fixed it for me (cygwin/tmux 2.4)

**Comment by bruno-** [comment]
Hi guys,
tmux 2.5 was released shortly after 2.4 because of incompatibilities introduced in that release.

I'm just testing this on OSX, tmux 2.5 and all seems to work ok. Can you please update to 2.5 and test on that version? If you distro doesn't have the package for 2.5 yet [please consider building from source](https://raw.githubusercontent.com/tmux/tmux/master/README), it's not hard.

**Comment by boweevil** [comment]
I just built tmux-2.5 from source and tested on Fedora 25.  It's still not working for me.

**Comment by boweevil** [comment]
Okay, I have a little more info this time.  This was a fresh install of Fedora 25 and I had forgotten to install xclip.  I discovered this when I went to test on tmux-2.3 again.  I got the warning that the tmux-yank dependencies weren't installed.  I never received that warning on tmux-2.5.  There is no action at all.  The selection just stays selected until I hit escape.

I installed xclip and then retested on both tmux-2.3 and tmux-2.5.  tmux-yank works on 2.3 but not on 2.5.

Hope this helps.

**Comment by jayywolff** [comment]
It's finally working for me on my Arch Linux box. 
Just make sure you have the lastest version of tmux, xclip, and update your TPM packages.
Ive noticed xsel does not work for me. Only xclip works. 

Im on tmux 2.5, xclip 0.13

**Comment by matt1003** [comment]
Hi guys, I have tired the following and have not had any luck:
- ubuntu 16.04
- tmux 2.5 (built from source)
- tmux-yank commit 68c5c7c
- xsel 1.2.0 and xclip 0.12

Again, the only functionality that appears to be working is the copy pwd.

@jayywolff, how did you install xclip 0.13?

**Comment by boweevil** [comment]
Okay, latest test was the following:
Fedora 25
tmux-2.5 (compiled from source)
xclip version 0.12
and I tested the following tmux-yank tags:
v0.0.4
v1.0.0
v2.0.0
v2.1.0
v2.2.0

I get the same behaviour on each tag.  I relaunched tmux after checking out each tag.

**Comment by boweevil** [comment]
Sorry, just tested with commit 68c5c7ca6f39159cbab447d61021b1e7e8a7c1fe and it is now working as expected.

**Comment by jayywolff** [comment]
@matt1003  `pacman -S xclip`
I'm on Arch, not Ubuntu.

**Comment by boweevil** [comment]
It looks like 375fbd8913667b39b36738a7bd45d8bc244d75ec is what fixes it for me.

**Comment by docwhat** [comment]
@boweevil: Thanks for the comprehensive troubleshooting.  Is it working for you now?

@matt1003: Do you have the latest tmux-yank version installed and being used (e.g. use TPM to upgrade).

**Comment by boweevil** [comment]
@docwhat Yes, it is working for me now on tmux 2.5 and tmux-yank commit 68c5c7ca6f39159cbab447d61021b1e7e8a7c1fe

**Comment by matt1003** [comment]
@docwhat: I now have tmux-yank 68c5c7c working with tmux-2.5. Previously I had been running my tmux-2.5 build directly from the source/build directory; however doing a proper `sudo make install` and running my tmux-2.5 build from `/usr/local/bin` has resolved the issue.

I can confirm that the following is now working:
- ubuntu 16.04
- tmux 2.5 (built from source and correctly installed)
- tmux-yank commit 68c5c7c
- xsel 1.2.0 and xclip 0.12
