### ISSUE TITLE
Nested sessions

### ISSUE THREAD

**Issue by vdun** [tmux-plugins/tmux-yank#97]
Does not work properly on nested sessions

**Comment by bruno-** [comment]
I confirm this issue.

I'm not sure if there are ways around it. It's just the limitation of the whole environment. So, I'd timidly say this is a "wont fix" problem, just because I don't know how would I address it.

**Comment by docwhat** [comment]
In theory this could work, but the keystrokes would be horrible.

There is no easy way to work through `tmux` encoding/decoding terminal codes twice.

"Won't fix" but I'd review a PR if someone had a clever thought.

**Comment by samogot** [comment]
Can someone please explain why this is not working, what are the difficulties and what is the theory in which it might work with terrible keystrokes? I'm creating plugin for handling nested sessions over ssh and tmux-yank is the only think I am missing in such setup. I am willing to (at least try to) contribute.

I tried to look in sources and so far I don't understand how it even works over ssh at all. I mean if I don't run tmux on local (mac) machine, then ssh to remote (linux) machine, run tmux there and use yank - I magically got selected text in local machine clipboard (although I don't see any special ssh handling, from the code it seems like the text should have been yanked to remote clipboard that I don't have access to over ssh). When I add tmux session on local machine everything breaks - even is I correctly select and yank something in nested (remote) tmux - I don't get the text in local clipboard anymore.

**Comment by samogot** [comment]
Oh, everything works just fine. The only thing that needs to be done is to turn on set-clipboard option. Sorry for necroposting :)
